### ISSUE TITLE
Using never to return from Area::getRoomById(...)

### ISSUE THREAD

**Issue by rogersm** [Ranvier-TS/core-ts#12]
Folks,

 why are we doing typing the return from Area::getRoomById with never?

    getRoomById(id: string): Room | never {
		const room = this.rooms.get(id);
		if (!room) {
			throw new Error(`Area did not find Room with id: [${id}]`);
		}
		return room;
	}

Never should be used for: 

- A function never returns (e.g. if the function body has while(true){})
- A function always throws (e.g. in function foo(){throw new Error('Not Implemented')} the return type of foo is never)

And in this case we return (room) or we may (but not always) thrown an Error.

Shouldn't this be:

getRoomById(id:string): **Room** { ... }

**Comment by seanohue** [comment]
I've seen `never` used to annotate the fact that the method returns an error but if that's an antipattern we can remove it

**Comment by rogersm** [comment]
That would be my recommendation. 

[Typescript Deep Dive Book describes the use of never in detail.](https://basarat.gitbook.io/typescript/type-system/never)

**Comment by seanohue** [comment]
Makes sense to me -- let's ditch it, then.
